name: continuous intergration

on:
  push:
    branches:
      -main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - name: checkout code
           uses: actions/checkout@v2

         - name: setup DotNet 5
           uses: actions/setup-dotnet@v1
           with:
             donet-version: '6.0.x'

         - name: restore dependencies
           run: dotnet restore

         - name: Build App
           run: dotnet build -c Release --no-restore

